"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GAME_MODE_LIST = exports.GAME_MODES = void 0;
exports.getGameMode = getGameMode;
exports.GAME_MODES = {
    classic: {
        id: "classic",
        name: "Klasický Duel",
        tagline: "Originální TikTok zážitek",
        description: "Střídavě zastavuješ stopky a tipuješ svůj vlastní čas. Kdo je přesnější, získá bod.",
        rules: [
            "Dva hráči na tah — ostatní sledují jako diváci",
            "Hráč A: START → STOP → tipni svůj čas",
            "Hráč B: totéž",
            "Bližší odhad získává bod",
            "První se 3 body vyhrává zápas",
        ],
        minPlayers: 2,
        maxPlayers: 8,
        winTarget: 3,
        icon: "Swords",
        color: "from-violet-500 to-purple-600",
        difficulty: "lehká",
    },
    sync: {
        id: "sync",
        name: "Synchronní Sprint",
        tagline: "Oba najednou, kdo má lepší vnitřní hodiny?",
        description: "Oba duelisté startují a zastavují své stopky současně — bez čekání na soupeře. Pak oba tipují.",
        rules: [
            "Oba hráči mají vlastní stopky",
            "START a STOP kdykoliv chceš — nezávisle na soupeři",
            "Až oba zastaví, zadáte odhady najednou",
            "Menší chyba = bod",
            "První se 3 body vyhrává",
        ],
        minPlayers: 2,
        maxPlayers: 8,
        winTarget: 3,
        icon: "Zap",
        color: "from-amber-500 to-orange-600",
        difficulty: "střední",
    },
    target: {
        id: "target",
        name: "Cílový Čas",
        tagline: "Žádné stopky — čistá koncentrace",
        description: "Server zvolí tajný cílový čas. Bez běžících stopek musíš odhadnout přesně tu hodnotu.",
        rules: [
            "Každé kolo má nový cíl (např. 00:07:50)",
            "Cíl vidíš před zadáním odhadu",
            "Všichni hráči tipují současně",
            "Nejpřesnější odhad = bod",
            "První se 3 body vyhrává",
        ],
        minPlayers: 2,
        maxPlayers: 8,
        winTarget: 3,
        icon: "Crosshair",
        color: "from-cyan-500 to-blue-600",
        difficulty: "střední",
    },
    ghost: {
        id: "ghost",
        name: "Duch Soupeře",
        tagline: "Tipuješ čas protivníka, ne svůj",
        description: "Soupeř zastaví stopky a ty musíš uhodnout, na jakém čase skončil — aniž bys viděl výsledek.",
        rules: [
            "Hráč A zastaví stopky → hráč B tipuje A-in čas",
            "Pak se role prohodí",
            "Každý správný tip soupeřova času = bod",
            "První se 3 body vyhrává",
        ],
        minPlayers: 2,
        maxPlayers: 8,
        winTarget: 3,
        icon: "Ghost",
        color: "from-emerald-500 to-teal-600",
        difficulty: "těžká",
    },
    memory: {
        id: "memory",
        name: "Paměťový Blitz",
        tagline: "Stopky zmizí, mozek pracuje",
        description: "Stopky běží jen 2 sekundy viditelně, pak se skryjí. Zastav je naslepo a tipni přesný čas.",
        rules: [
            "Po STARTu vidíš čas jen 2 sekundy",
            "Displej se skryje, ale stopky běží dál",
            "Zastav naslepo, kdy si myslíš, že je správný moment",
            "Pak tipni, na jakém čase jsi zastavil",
            "Přesnější hráč získává bod",
        ],
        minPlayers: 2,
        maxPlayers: 8,
        winTarget: 3,
        icon: "Brain",
        color: "from-pink-500 to-rose-600",
        difficulty: "těžká",
    },
    battle_royale: {
        id: "battle_royale",
        name: "Battle Royale",
        tagline: "Poslední přeživší vyhrává",
        description: "Všichni najednou měří čas. Nejméně přesný hráč je eliminován. Zůstane jen jeden šampion.",
        rules: [
            "Minimálně 3 hráči",
            "Každé kolo: všichni startují a zastavují vlastní stopky",
            "Všichni tipují svůj čas",
            "Nejhorší odhad = eliminace",
            "Poslední hráč ve hře vyhrává",
        ],
        minPlayers: 3,
        maxPlayers: 8,
        winTarget: 1,
        icon: "Flame",
        color: "from-red-500 to-orange-600",
        difficulty: "extrémní",
    },
    sudden_death: {
        id: "sudden_death",
        name: "Sudden Death",
        tagline: "Jedno kolo rozhodne vše",
        description: "Žádná dlouhá série kol. Všichni změří čas, jeden odhad — nejpřesnější okamžitě vyhrává celou hru.",
        rules: [
            "Všichni hráči hrají najednou",
            "START → STOP → tipni svůj čas",
            "Jediné kolo",
            "Nejpřesnější odhad vyhrává celou hru",
        ],
        minPlayers: 2,
        maxPlayers: 8,
        winTarget: 1,
        icon: "Skull",
        color: "from-zinc-600 to-zinc-900",
        difficulty: "střední",
    },
};
exports.GAME_MODE_LIST = Object.values(exports.GAME_MODES);
function getGameMode(id) {
    return exports.GAME_MODES[id];
}
